[project]
name = "TriageMCP"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "die-python (>=0.4.0,<0.5.0)",
    "pefile (>=2024.8.26,<2025.0.0)",
    "yara-python (>=4.5.4,<5.0.0)",
    "mcp[cli] (>=1.21.2,<2.0.0)",
]
